python train.py \
    --dataset_dir dataset/triviaqa_traj_llama \
    --mapping dataset/triviaqa_traj_llama/token_mapping.json \
    --output_dir weight/triviaqa_traj_llama/full \
    --train_new_embeddings_only \
    --epochs 1 \
    --use_kl_distillation \
    --kl_weight 1.0 \
    --teacher_model_name meta-llama/Llama-3.1-8B-Instruct \
    --model_name meta-llama/Llama-3.1-8B-Instruct \
    --batch_size 1